---
sidebar: sidebar
permalink: workflows_infra/wf_add_cluster.html
keywords:
summary: You can add a cluster so that Astra can the manage it to protect the various apps and resources.
---

= Add a cluster using credentials
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can add a cluster so that Astra can the manage it to protect the various apps and resources.

[NOTE]
Beginning with the Astra 22.11, you can create a cluster on either Astra Control Center or Astra Control Service.

=== 1. Obtain the Kubeconfig file

You need to obtain a copy of the kubconfig file from your Kubernetes administrator or service.

=== 2. Prepare the Kubeconfig file

Before using the kubeconfig file, you need to perform the following operations:

. Convert the file from YAML format to JSON
. Encode the JSON file in base64.

=== 3. Create the cluster

Perform the following REST API call.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/accounts/{account_id}/core/v1/users
|===

===== Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl examples for this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|include
|Query
|No
|Optionally select the values you want returned in the response.
|===

===== Curl example: Return all data for all users
[source,curl]
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/users' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'

===== Curl example: Return the first name, last name, and id for all users
[source,curl]
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/users?include=firstName,lastName,id' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'

===== JSON output example
[source,curl]
{
  "items": [
    [
    "David",
    "Anderson",
    "844ec6234-11e0-49ea-8434-a992a6270ec1"
    ],
    [
      "Jane",
      "Cohen",
      "2a3e227c-fda7-4145-a86c-ed9aa0183a6c"
    ]
  ],
  "metadata": {}
}
