---
sidebar: sidebar
permalink: additional/rbac.html
keywords:
summary:
---

= RBAC security
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Astra REST API supports role-based access control (RBAC) to restrict access to the system functions. and

== Astra roles

Each Astra user is assigned to a single role which determines the actions that can be performed. The roles are arranged in a hierarchy as described in the table below.

[cols="15,85"*,options="header"]
|===
|Role
|Description
|Owner
|Has all the permissions of the Admin role and can also delete Astra accounts.
|Admin
|Has all the permissions of the Member role and can also invite users to join an account.
|Member
|Can fully manage the Astra application and compute resources.
|Viewer
|Restricted to only viewing resources.
|===

== Enhanced RBAC with namespace granularity

[NOTE]
This feature was introduced with the 22.04 release of the Astra REST API.

When a role binding is established for a specific user, a constraint is available to limit which namespaces the user has access to. There are several ways the constraint can be defined as described in the table below.

[cols="20,80"*,options="header"]
|===
|Type
|Description
|All
|XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
|NONE
|XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
|List
|XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
|Label
|XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
|===
