---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/get-accounts-core-v1-credentials-.html'
summary: 'Retrieve a credential'
---

= Retrieve a credential

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials/{credential_id}`#



Returns the stored Credential API resource in the JSON response body.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|credential_id
|string
|path
|True
a|ID of the credential collection to list


|===

== Response

```
Status: 200, Returns the stored Credential API resource in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-credential"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|True
a|JSON string containing a user-specified name.
When a credential is created for a user, the name will be set to the UUID of that user.
Defined values are:

* Minimum length: 1
* Maximum length: 127


|keyType
|string
|False
a|JSON string containing an optional user-specified data validation type descriptor for the contents of the keyStore.
Extended update constraints:

* If a keyType does not exist in the resource and is not specified in an update, the keyType must not continue to exist in the updated resource.
* If a keyType does not exist in the resource and is specified in an update, the keyType must be added to the resource and validation must be performed. If the validation fails, the update will fail.
* If a keyType exists in the resource and is not specified in an update, the keyType must be preserved.
* If a keyType exists in the resource and is specified in an update, and the keyType specified matches the existing keyType, the keyType must be preserved.
* If a keyType exists in the resource and is specified in an update, and the keyType specified is different from the existing keyType, the update will fail.
Defined values are:
* "generic" - The credential is a generic collection of data. This is equivalent to not including a keyType.
* Extended validation is performed as follows:
* One or more strings must exist in the keyStore.
* Every string in the keyStore must have a value encoded in base64.
* "passwordHash" - The credential is a password hash.
* Extended validation is performed as follows:
* The name of the credential must be unique.
* The name of the credential must be equal to a valid user resource ID.
* The name of the credential must not be altered.
* The corresponding user resource must have an "authProvider" of "local".
* A "cleartext" string must exist within the keyStore with a value containing a base64-encoded cleartext password:
* The password cleartext must conform to the account's password policy.
* The password is stored as a hash.
* A "change" string must exist within the keyStore with a value containing a base64-encoded string "true" or "false".
* A credential of type passwordHash can only be deleted if the user ID indicated by the name does not exist.
* "apikey" - The credential is an API key.
* Extended validation is performed as follows:
* An "apikey" string must exist within the keyStore, with a value containing a base64-encoded arbitrary string.
* "kubeconfig" - The credential is a kubeconfig.
* Extended validation is performed as follows:
* A "base64" string must exist within the keyStore, with a value containing a base64-encoded JSON kubeconfig file.
* The kubeconfig file must only describe a single cluster.
* No other fields can exist within the keyStore.
* "certificate" - The credential is a PEM-encoded certificate
* Extended validation is performed as follows:
* A "certificate" string must exist within the keyStore, with a value containing a base64-encoded PEM certificate.
* "privkey" - The credential is a PEM-encoded private key.
* Extended validation is performed as follows:
* A "privkey" string must exist within the keyStore, with a value containing a base64-encoded PEM private key.
* "s3" - Indicates the credentials are for Simple Storage Service (S3) access.
* Extended validation is performed as follows:
* An "accessKey" string must exist within the keyStore with a value containing a base64-encoded S3 access key.
* An "accessSecret" string must exist within the keyStore with a value containing a base64-encoded S3 access secret.


|valid
|string
|True
a|JSON string describing whether the credential is valid for use. Default value, if omitted, is "true".
Defined values are:

* "true" - The credential is eligible for use.
* "false" - The credential must not be used.


|validFromTimestamp
|string
|False
a|JSON string containing a timestamp indicating when the credential is valid. These are used for credential rotation.
Defined values are:

* Conforms to the ISO-8601 Date Time Schema


|validUntilTimestamp
|string
|False
a|JSON string containing a timestamp indicating when the credential is no longer valid. These are used for credential rotation.
Defined values are:

* Conforms to the ISO-8601 Date Time Schema


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|True
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-credential",
  "version": "1.1",
  "id": "58e26f6a-a631-5122-8e0e-7afe306675c0",
  "name": "myCert",
  "valid": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
====

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid query parameters


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


//end collapsible .Definitions block
====
