---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/get-accounts-core-v1-notifications.html'
summary: 'List all notifications'
---

= List all notifications

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/notifications`#



Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|include
|string
|query
|False
a|Indicates which fields should be returned when listing a collection.

URL examples: "include=id", "include=id,name"

OpenAPI examples: "id"

* example: id,summary


|limit
|string
|query
|False
a|Indicates the maximum number of resources to return when listing a collection.

URL examples: "limit=2"

OpenAPI examples: "2"

* example: 4


|filter
|string
|query
|False
a|Indicates which fields should be matched in order to return a resource when listing a collection.

Supported operators are:

* eq - Equality
* lt/gt - Less than/Greater than
* lte/gte - Less than or equals to/Greater than or equals to

URL example: "filter=field%20eq%20%27value%27"

OpenAPI examples: "field eq 'value'"


|orderBy
|string
|query
|False
a|Indicates the sort order of resource when listing a collection.

URL examples: "orderBy=name", "orderBy=name%20desc"

OpenAPI examples: "name desc"


|skip
|string
|query
|False
a|Indicates the number of resources to skip over when listing a collection.

URL examples: "skip=1"

OpenAPI examples: "1"


|count
|string
|query
|False
a|Indicates if the total number of resources should be returned in the metadata object.

URL examples: "count=true"

OpenAPI examples: "true"

* example: true


|continue
|
|query
|False
a|Indicates the token to resume listing from.

URL examples: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPI examples: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>


|===

== Response

```
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|items
|array[Any of: link:#notification_1_3_get_response_body[notification_1.3_get_response_body], array[]]
|True
a|

|metadata
|link:#type_astra_metadata_list[type_astra_metadata_list]
|True
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-notifications",
  "version": "1.3",
  "items": [
    [
      "4f8273ee-883d-47f0-a512-9e27b6285f20",
      "Discovering Applications in Cluster"
    ],
    [
      "1cdd26dc-5eb0-4cf4-a0c1-39a9b83720e1",
      "Application Discovered"
    ],
    [
      "275a8c6f-ebf6-4d10-b671-77d1b8c7c0a6",
      "Application Discovery Failed"
    ],
    [
      "4325f971-ca9c-4a52-bc9a-da6ec62e6bfe",
      "Application Discovered"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
====

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid query parameters


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#data]
[.api-collapsible-fifth-title]
data

JSON object containing additional event-specific information.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|ttl
|number
|False
a|JSON number indicating the number of seconds (since the eventTime) that the event will be retained.
This field is only included when an event is automatically deleted after the specified number of seconds.
When deleted, if the event has a notification destination, all associated notifications are also deleted.
When deleted, if the event has a banner destination, the banner is also removed.
The absence of this field (or a value of "0") means that an event will not be automatically deleted.


|isAcknowledgeable
|string
|False
a|JSON string indicating whether the banner is dismissible.
Defined values are:

* "true" - The banner is dismissible
* "false" - The banner is not dismissible


|===


[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata]
[.api-collapsible-fifth-title]
type_astra_metadata

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|True
a|

|creationTimestamp
|string
|True
a|

|modificationTimestamp
|string
|True
a|

|createdBy
|string
|True
a|

|modifiedBy
|string
|False
a|

|===


[#notification_1_3_get_response_body]
[.api-collapsible-fifth-title]
notification_1.3_get_response_body

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-notification"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"
* "1.2"
* "1.3"


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|True
a|JSON string containing a dot notation (.) hierarchical name for the event.
Defined values are:

* Minimum length: 3
* Maximum length: 127
* Defined regex is: "{caret}(([a-z])_(\.))_([a-z])+$"


|sequenceCount
|number
|True
a|JSON number containing a sequence count.
The number is incremented by the system each time a new event is received.


|summary
|string
|True
a|JSON string containing the short-form (less than 40 characters) summary of the event.
Defined values are:

* Minimum length: 3
* Maximum length: 79


|eventTime
|string
|True
a|JSON string containing a timestamp that indicates when an event occurred.
Defined values are:

* Conforms to the ISO-8601 Date Time Schema


|source
|string
|True
a|JSON string containing the lowercase name of the service generating an event.
Defined values are:

* Minimum length: 1
* Maximum length: 19
* Defined regex is: "{caret}([a-z-])*$"


|resourceID
|string
|True
a|JSON string containing the resource ID associated with an event.
Defined values are:

* Conforms to the Astra Identifier Schema


|additionalResourceIDs
|array[string]
|True
a|JSON array of JSON strings, each containing a resource ID of an additional resource associated with the event. Although the "resourceID" field contains the primary resource associated with this event, this field contains any number of additional resource IDs to be associated with the same events.
If no additional resources are associated with the event, the array will be empty.
Defined values are:

* Conforms to the Astra Identifier Schema


|resourceType
|string
|True
a|JSON string containing the media type of the resource associated with an event.
Defined values are:

* Minimum length: 4
* Maximum length: 79
* Defined regex is: "{caret}application\/astra-([a-zA-Z])+$"


|correlationID
|string
|True
a|JSON string containing a UUIDv4 correlation ID that allows related events to be grouped together.
Defined values are:

* Conforms to the Astra Identifier Schema


|severity
|string
|True
a|JSON string containing one of the following values that indicate the severity of an event.
Defined values are:

* "cleared" - Indicates that a previously reported event describing a condition is no longer active. An event with severity "cleared" will use the same summary and correlation ID to allow it to be matched up.
* "indeterminate" - Indicates that the severity cannot be determined.
* "informational" - Indicates a change in state that is both expected and normal (not defined in X.733).
* "warning" - Indicates the detection of a potential or impending service affecting fault, before any significant effects have been felt.
* "critical" - Indicates that a service affecting condition has occurred and immediate corrective action is required.
Definitions for "cleared", "indeterminate", "warning" and "critical" are based on definitions in clause 8.1.2.3 of CCITT X.733.


|class
|string
|True
a|JSON string containing one of the following values that indicate the class of the event.
Defined values are:

* "system" - The event is related to an internal event or request.
* "user" - The event is related to a user-initiated event or request.
* "security" - The event is related to a security issue.


|description
|string
|True
a|JSON string containing a long-form descriptive text about the event.
Defined values are:

* Minimum length: 3
* Maximum length: 1023


|descriptionURL
|string
|False
a|JSON string containing the URL that enables and links a button in the banner to external documentation.
Defined values are:

* Minimum length: 3
* Maximum length: 4095


|correctiveAction
|string
|False
a|JSON string containing a long-form descriptive text about what corrective action should be taken in response to the event.
Defined values are:

* Minimum length: 3
* Maximum length: 1023


|correctiveActionURL
|string
|False
a|JSON string containing the URL that links a button in the banner to a page within the UI to fix the issue.
Defined values are:

* Minimum length: 3
* Maximum length: 4095


|visibility
|array[string]
|False
a|JSON array of JSON strings, each indicating an RBAC role permitted to view the event. Roles are OR-defined together. Optional.
If omitted, a user with any RBAC role can view the event.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|destinations
|array[string]
|False
a|JSON array of JSON strings, each indicating an additional destination for the event. These allow a service to provide hints about where an event must be routed in addition to the Activity service's activity log. Optional.
Defined values are:

* "notification" - The event is marked as a notification, and will be accessible through the notifications API endpoint.
* "banner" - The event is marked as a banner.
* "support" - The event is marked as a support-related event.


|resourceURI
|string
|False
a|JSON string containing the URI associated with the event. Only included for events related to API operations.
Defined values are:

* Minimum length: 3
* Maximum length: 4095


|resourceCollectionURL
|array[string]
|False
a|JSON array of JSON strings, each indicating the fully-expanded access URL of the resource associated with the event.
Defined values are:

* Minimum length: 1
* Maximum length: 1023


|resourceMethod
|string
|False
a|JSON string containing the HTTP method invoked. Included only for events related to API operations.
Defined values are:

* "options" - OPTIONS API operation
* "post" - POST API operation
* "get" - GET API operation
* "put" - PUT API operation
* "delete" - DELETE API operation


|resourceMethodResult
|string
|False
a|JSON string containing the result of the HTTP method invoked. Only included for events related to the API operations.
Defined values are:

* Defined regex is: "{caret}[1-5][0-9]\{2}$"


|userID
|string
|False
a|JSON string containing the user ID associated with an event. Only included for events associated with the user-initiated actions.
Defined values are:

* Conforms to the Astra Identifier Schema


|accountID
|string
|False
a|JSON string containing the account ID associated with an event. Only included for events associated with an account.
Defined values are:

* Conforms to the Astra Identifier Schema


|data
|link:#data[data]
|False
a|JSON object containing additional event-specific information.


|metadata
|link:#type_astra_metadata[type_astra_metadata]
|True
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema


|===


[#type_astra_metadata_list]
[.api-collapsible-fifth-title]
type_astra_metadata_list

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|continue
|string
|False
a|

|count
|number
|False
a|

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


//end collapsible .Definitions block
====
