---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/get-accounts-k8s-v1-apps-appsnaps-.html'
summary: 'Retrieve an application snapshot'
---

= Retrieve an application snapshot

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appSnaps/{appSnap_id}`#



Returns the stored Application Snapshot API resource in the JSON response body.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|app_id
|string
|path
|True
a|ID of the containing app resource


|appSnap_id
|string
|path
|True
a|ID of the appSnap collection to list


|===

== Response

```
Status: 200, Returns the stored Application Snapshot API resource in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-appSnap"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"
* "1.2"
* "1.3"


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|True
a|JSON string containing a user-specified name for the snapshot. If not specified, or when snapshots are initiated by a schedule, the system assigns a name for the snapshot.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* Conforms to the DNS 1123 Label Schema


|bucketID
|string
|False
a|JSON string containing an optional bucket ID that indicates where the snapshot will be stored on create. If not specified, a default bucket on the cluster is used. If no default bucket is specified on the cluster, the corresponding cloud default bucket will be used.
If the cloud default bucket is not available, an error will be returned on create. Defined values are:

* Conforms to the Astra Identifier Schema


|scheduleID
|string
|False
a|JSON string containing an optional schedule ID that indicates that the snapshot was triggered by a schedule and specifies which schedule triggered the snapshot. Only present for snapshots initiated by a schedule.
Defined values are:

* Conforms to the Astra Identifier Schema


|snapshotAppAsset
|string
|False
a|JSON string containing the ID of the application asset corresponding to the snapshot. This field will be returned when the state of the application snapshot is "completed".
Defined values are:

* Conforms to the Astra Identifier Schema


|state
|string
|True
a|JSON string containing a value indicating the operational state of the snapshot.
Defined values are:

* "pending" - The application snapshot is scheduled for discovery
* "discovering" - The application snapshot is in the process of being discovered
* "running" - The application snapshot is running normally
* "completed" - The application snapshot has completed
* "failed" - The application snapshot is in a permanent failure state
* "removed" - The application snapshot is not currently accessible
* "deleting" - The application snapshot is being deleted
* "unknown" - The application snapshot state cannot be determined


|stateUnready
|array[string]
|True
a|JSON array of JSON strings, each indicating a reason why an application snapshot is unable to transition to "running", or why it has transitioned to "failed".
Defined values are:

* Minimum length: 1
* Maximum length: 127


|stateDetails
|array[link:#type_astra_stateDetail[type_astra_stateDetail]]
|False
a|JSON array of JSON objects which lists additional details about the current state, including why the current state was reached.
If no details are available, this array will be empty.
Defined values are:

* Minimum Items: 0


|hookState
|string
|False
a|JSON string containing a value indicating the state of any execution hook or hooks running as a part of a snapshot.
Defined values are:

* "failed" - One or more execution hooks have failed
* "success" - There were zero or more applicable hooks and all were successful


|hookStateDetails
|array[link:#type_astra_stateDetail[type_astra_stateDetail]]
|False
a|JSON array of JSON objects which lists additional details about why "hookState" transitioned into "failed".
If no details are available, this array will be empty.

* Minimum items: 0


|metadata
|link:#type_astra_metadata[type_astra_metadata]
|True
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-appSnap",
  "version": "1.3",
  "id": "c2cc5c22-ed0e-5c2b-8b7e-0fb81727f617",
  "name": "app-name-245",
  "bucketID": "0afbe357-a717-4c7a-8b3d-d0368959c8de",
  "scheduleID": "1fe83650-9b3c-41ef-bb25-a2910c19c33e",
  "state": "pending",
  "stateUnready": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
====

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidParams
|array[link:#invalidParams[invalidParams]]
|False
a|List of invalid query parameters


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#additionalDetails]
[.api-collapsible-fifth-title]
additionalDetails


[#type_astra_stateDetail]
[.api-collapsible-fifth-title]
type_astra_stateDetail

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|additionalDetails
|link:#additionalDetails[additionalDetails]
|False
a|

|===


[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata]
[.api-collapsible-fifth-title]
type_astra_metadata

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|True
a|

|creationTimestamp
|string
|True
a|

|modificationTimestamp
|string
|True
a|

|createdBy
|string
|True
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


//end collapsible .Definitions block
====
