---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/post-accounts-k8s-v1-apps-schedules.html'
summary: 'Create a new schedule for an app'
---

= Create a new schedule for an app

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/schedules`#



Indicates desired values for the Schedule API resource to be created.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|app_id
|string
|path
|True
a|ID of the containing app resource


|===

== Request Body

Indicates desired values for the Schedule API resource to be created.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-schedule"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"
* "1.2"
* "1.3"


|name
|string
|True
a|JSON string containing a name of the schedule.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|enabled
|string
|False
a|JSON string indicating if a schedule is active.
Defined values are:

* "true" - The schedule is active
* "false" - The schedule is not active
If not specified, the default value is "true".


|granularity
|string
|True
a|JSON string indicating the granularity of the schedule.
Defined values are:

* "hourly"
* "daily"
* "weekly"
* "monthly"
* "custom"


|minute
|string
|False
a|JSON string containing a numeric value indicating the minute of the hour (0 - 59) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[0-9]\|[1-5][0-9]$"
This field is present if granularity is set to "hourly", "daily", "weekly", or "monthly". It will be returned with value "0" for custom schedules.


|hour
|string
|False
a|JSON string containing a numeric value indicating the hour of the day (0 - 23) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[0-9]\|[1][0-9]\|[2][0-3]$"
This field is present if granularity is set to "daily", "weekly", or "monthly".


|dayOfWeek
|string
|False
a|JSON string containing a numeric value indicating the day of the week (0-7) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[0-7]$"
This field is only present if granularity is set to "weekly".


|dayOfMonth
|string
|False
a|JSON string containing a numeric value indicating the day of the month (1-31) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[1-9]\|[1-2][0-9]\|[3][0-1]$"
This field is only present if granularity is set to "monthly".


|recurrenceRule
|string
|False
a|JSON string containing an RFC-5545 Section 3.8.5.3. Recurrence Rule.
For the DTSTART parameter, only UTC timestamps (denoted by the "Z" suffix) are supported, and only timestamps before the current time are supported.
For the RECUR rule parts, "FREQ" and "INTERVAL" are the only rule parts supported.
For the FREQ rule part, "MINUTELY" and "HOURLY" are the only values supported.
This field is only present if granularity is set to "custom".


|snapshotRetention
|string
|True
a|JSON string containing a positive numeric value indicating how many snapshots to retain. Zero indicates that snapshots should be deleted after taking a backup.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* Defined regex is: "{caret}(0\|([1-9][0-9]*))$"


|backupRetention
|string
|True
a|JSON string containing a positive numeric value indicating how many backups to retain. Zero indicates that no backups should be created.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* Defined regex is: "{caret}(0\|([1-9][0-9]*))$"


|bucketID
|string
|False
a|JSON string containing an optional bucket ID indicating where the backup must be stored on create. If not specified, a system-selected bucket will be used.
Defined values are:

* Conforms to the Astra Identifier Schema


|replicate
|string
|False
a|JSON string indicating if the schedule triggers AppMirror replication for each snapshot. Only takes effect if the application has an AppMirror relationship defined.
Defined values are:

* "true" - The schedule triggers AppMirror replication
* "false" - The schedule does not trigger AppMirror replication
If not specified, the default value is "false".


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|False
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12"
}
====

== Response

```
Status: 201, Returns the newly created schedule resource in the JSON response body.
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-schedule"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"
* "1.2"
* "1.3"


|id
|string
|True
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|True
a|JSON string containing a name of the schedule.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|enabled
|string
|True
a|JSON string indicating if a schedule is active.
Defined values are:

* "true" - The schedule is active
* "false" - The schedule is not active
If not specified, the default value is "true".


|granularity
|string
|True
a|JSON string indicating the granularity of the schedule.
Defined values are:

* "hourly"
* "daily"
* "weekly"
* "monthly"
* "custom"


|minute
|string
|True
a|JSON string containing a numeric value indicating the minute of the hour (0 - 59) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[0-9]\|[1-5][0-9]$"
This field is present if granularity is set to "hourly", "daily", "weekly", or "monthly". It will be returned with value "0" for custom schedules.


|hour
|string
|False
a|JSON string containing a numeric value indicating the hour of the day (0 - 23) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[0-9]\|[1][0-9]\|[2][0-3]$"
This field is present if granularity is set to "daily", "weekly", or "monthly".


|dayOfWeek
|string
|False
a|JSON string containing a numeric value indicating the day of the week (0-7) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[0-7]$"
This field is only present if granularity is set to "weekly".


|dayOfMonth
|string
|False
a|JSON string containing a numeric value indicating the day of the month (1-31) to execute the schedule.
Defined values are:

* Defined regex is: "{caret}[1-9]\|[1-2][0-9]\|[3][0-1]$"
This field is only present if granularity is set to "monthly".


|recurrenceRule
|string
|False
a|JSON string containing an RFC-5545 Section 3.8.5.3. Recurrence Rule.
For the DTSTART parameter, only UTC timestamps (denoted by the "Z" suffix) are supported, and only timestamps before the current time are supported.
For the RECUR rule parts, "FREQ" and "INTERVAL" are the only rule parts supported.
For the FREQ rule part, "MINUTELY" and "HOURLY" are the only values supported.
This field is only present if granularity is set to "custom".


|snapshotRetention
|string
|True
a|JSON string containing a positive numeric value indicating how many snapshots to retain. Zero indicates that snapshots should be deleted after taking a backup.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* Defined regex is: "{caret}(0\|([1-9][0-9]*))$"


|backupRetention
|string
|True
a|JSON string containing a positive numeric value indicating how many backups to retain. Zero indicates that no backups should be created.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* Defined regex is: "{caret}(0\|([1-9][0-9]*))$"


|bucketID
|string
|False
a|JSON string containing an optional bucket ID indicating where the backup must be stored on create. If not specified, a system-selected bucket will be used.
Defined values are:

* Conforms to the Astra Identifier Schema


|replicate
|string
|False
a|JSON string indicating if the schedule triggers AppMirror replication for each snapshot. Only takes effect if the application has an AppMirror relationship defined.
Defined values are:

* "true" - The schedule triggers AppMirror replication
* "false" - The schedule does not trigger AppMirror replication
If not specified, the default value is "false".


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|True
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "id": "49cbc480-5f7d-51e2-8f30-52b9a83a03b1",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
====

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


[#invalidFields]
[.api-collapsible-fifth-title]
invalidFields

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid request body field


|reason
|string
|True
a|Reason why the request body field is invalid


|===


//end collapsible .Definitions block
====
