---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/put-accounts-.html'
summary: 'Modify an account'
---

= Modify an account

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}`#



Replaces the entire stored resource with the supplied JSON request body while preserving the key values that are not user-modifiable.

*Side Effects*

* Changing "isEnabled" from "false" to "true" sets "enabledTimestamp" to the current time.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the account collection to list

* example: {{.Account}}


|===

== Request Body

Replaces the entire stored resource with the supplied JSON request body while preserving the key values that are not user-modifiable.

*Side Effects*

* Changing "isEnabled" from "false" to "true" sets "enabledTimestamp" to the current time.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-account"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"


|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|False
a|JSON string containing a name for the account.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|state
|string
|False
a|JSON string containing a value indicating the operational state of the account.
Defined values are:

* "pending" - Changes can only be made to user and role resources under the account (default value)
* "active" - Changes can be made to any resource under the account
* "deletePending" - Users cannot log in, data protection operations are suspended, charges no longer accrue


|isEnabled
|string
|False
a|JSON string indicating the account is enabled.
Defined values are:

* "false" - Users are not permitted to use this account
* "true" - Users are permitted to use this account


|enabledTimestamp
|string
|False
a|JSON string containing the timestamp indicating when the account was last enabled.
If the account has never been enabled, this field is absent.
Defined values are:

* Conforms to the ISO-8601 Date Time Schema


|accountContact
|link:#accountContact[accountContact]
|False
a|JSON object containing user contact information to create an owner user at the time of account activation.


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|False
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-account",
  "version": "1.0",
  "name": "frightened-pine"
}
====

== Response

```
Status: 204, Indicates if the account resource was updated.
```

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#postalAddress]
[.api-collapsible-fifth-title]
postalAddress

JSON object containing a collection of JSON strings specifying an address. If this key does not exist, it indicates that an address has not been provided.
If this key exists, all six of the contained JSON strings will be present. If you provide nothing, the string will be empty.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|addressCountry
|string
|False
a|JSON string containing the country name or country code associated with the postal address, as specified in ISO 3166 Alpha-2.
Defined values are:

* Minimum length: 2
* Maximum length: 2


|addressLocality
|string
|False
a|JSON string containing the locality (for example, city) associated with the postal address.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|addressRegion
|string
|False
a|JSON string containing the region (for example, state) associated with the postal address.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|postalCode
|string
|False
a|JSON string containing the postal code associated with the postal address.
Defined values are:

* Minimum length: 1
* Maximum length: 31


|streetAddress1
|string
|False
a|JSON string containing the street address associated with the postal address.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|streetAddress2
|string
|False
a|JSON string containing optional ancillary street address information, post office box, and more.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|===


[#accountContact]
[.api-collapsible-fifth-title]
accountContact

JSON object containing user contact information to create an owner user at the time of account activation.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|firstName
|string
|False
a|JSON string containing a user specified long-form first name.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|lastName
|string
|False
a|JSON string containing a user specified long-form last name.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|companyName
|string
|False
a|JSON string containing the company name associated with the user. If this key does not exist, it indicates that a company name has not been provided.
Defined values are:

* Minimum length: 1
* Maximum length: 63
* This string is internally validated to prevent XSS, Unicode, directory traversal, and SQL-injection attacks.


|email
|string
|False
a|JSON strings containing a user specified email address.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|phone
|string
|False
a|JSON string containing the phone number of the user. If this key does not exist, it indicates that a phone number has not been provided.
Defined values are:

* Minimum length: 1
* Maximum length: 31


|postalAddress
|link:#postalAddress[postalAddress]
|False
a|JSON object containing a collection of JSON strings specifying an address. If this key does not exist, it indicates that an address has not been provided.
If this key exists, all six of the contained JSON strings will be present. If you provide nothing, the string will be empty.


|===


[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


[#invalidFields]
[.api-collapsible-fifth-title]
invalidFields

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid request body field


|reason
|string
|True
a|Reason why the request body field is invalid


|===


//end collapsible .Definitions block
====
