---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/put-accounts-core-v1-upgrades-.html'
summary: 'Modify an upgrade'
---

= Modify an upgrade

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#



Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.

*Side Effects*

* Upgrades are scheduled or run based on desired state.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|upgrade_id
|string
|path
|True
a|ID of the upgrade collection to list


|===

== Request Body

Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.

*Side Effects*

* Upgrades are scheduled or run based on desired state.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-upgrade"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"


|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|componentName
|string
|False
a|JSON string containing the name of the type of software that can be upgraded.
Defined values are:

* "acc"
* "acs"
* "trident"
* "kubernetes"


|componentInstance
|string
|False
a|JSON string containing the URI of the component that can be upgraded.
Defined values are:

* Minimum length: 3
* Maximum length: 4095


|componentID
|string
|False
a|JSON string containing a globally unique identifier of the component that can be upgraded.
Defined values are:

* Conforms to the Astra Identifier Schema


|upgradeVersion
|string
|False
a|JSON string containing the SemVer of the software image file that can be upgraded to.
Defined values are:

* Conforms to the SemVer Schema


|currentVersion
|string
|False
a|JSON string containing the current SemVer of the entity to be upgraded.
Defined values are:

* Conforms to the SemVer Schema


|dependencies
|array[string]
|False
a|JSON array of JSON strings, each containing the UUID of an upgrade that must be completed before this upgrade can proceed. Used to determine which upgrades will be performed as prerequisites and in which order.
Defined values are:

* Conforms to the Astra Identifier Schema


|state
|string
|False
a|JSON string containing a value indicating the operational state of the upgrade.
If auto-upgrade is enabled, upgrades will start in the "scheduled" state. Otherwise, upgrades will start in the "proposed" state.
Defined values are:

* "unavailable" - The upgrade is not available at this time
* "proposed" - The upgrade is proposed but will not automatically run until approved
* "scheduled" - The upgrade is approved but is not ready to be installed due to dependencies, time windows, or available resources
* "running" - The upgrade is in progress
* "complete" - The upgrade has completed
* "failed" - The upgrade did not complete


|stateDesired
|string
|False
a|JSON string containing a value indicating the desired state for "state".
This field is only included when the user can directly request a change in the state of the resource.
Defined values are:

* "proposed" - The upgrade is not approved and must not be performed
* "scheduled" - The upgrade is approved and must be performed in the specified time window
* "running" - The upgrade must be performed immediately, regardless of the time window


|stateDetails
|array[link:#type_astra_stateDetail[type_astra_stateDetail]]
|False
a|JSON array of JSON objects that lists additional details about the current "state".
If no details are available, this array will be empty.

* Minimum Items: 0


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|False
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "stateDesired": "running"
}
====

== Response

```
Status: 204, Indicates if the upgrade resource was updated.
```

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#additionalDetails]
[.api-collapsible-fifth-title]
additionalDetails


[#type_astra_stateDetail]
[.api-collapsible-fifth-title]
type_astra_stateDetail

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|additionalDetails
|link:#additionalDetails[additionalDetails]
|False
a|

|===


[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


[#invalidFields]
[.api-collapsible-fifth-title]
invalidFields

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid request body field


|reason
|string
|True
a|Reason why the request body field is invalid


|===


//end collapsible .Definitions block
====
