---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/put-accounts-topology-v1-storagebackends-.html'
summary: 'Modify a storage backend'
---

= Modify a storage backend

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/storageBackends/{storageBackend_id}`#



Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.

*Side Effects*

* Specifying a configuration version results in storage backend type-specific configuration changes being applied, which can include the initial installation of a storage backend.
* Specifying a configuration version might result in storageClass resources being added, modified, or removed.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|storageBackend_id
|string
|path
|True
a|ID of the storageBackend collection to list


|===

== Request Body

Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.

*Side Effects*

* Specifying a configuration version results in storage backend type-specific configuration changes being applied, which can include the initial installation of a storage backend.
* Specifying a configuration version might result in storageClass resources being added, modified, or removed.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-storageBackend"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"
* "1.2"
* "1.3"


|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|backendName
|string
|False
a|JSON string containing a user-specified name for the storage backend.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|backendType
|string
|False
a|JSON string containing a value indicating the type of the storage backend being represented.
Defined values are:

* "ontap" - The storage backend represents a NetApp ONTAP system
* enum: ["ontap"]
* example: ontap


|backendVersion
|string
|False
a|JSON string containing a value indicating the version of the storage backend being represented.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|backendCredentialsName
|string
|False
a|JSON string containing a value indicating the name of one or more credential resources used for the storage backend. Allows for credential rotation where multiple credential objects have the same name.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|configVersion
|string
|False
a|JSON string containing a value indicating the active configuration to be used by the storage backend.
Defined values are:

* Minimum length: 1
* Maximum length: 63


|state
|string
|False
a|JSON string containing a value indicating the operational state of the storage backend.
Defined values are:

* "discovered" - The storage backend has been discovered from a managed cluster
* "running" - The storage backend is running normally
* "unknown" - The state of the storage backend cannot be determined
* "failed" - The storage backend is in an unavailable state


|stateDesired
|string
|False
a|JSON string containing a value indicating the desired operational state of the storage backend.
Defined values are:

* "running" - The storage backend will be in a normal running state


|stateUnready
|array[string]
|False
a|JSON array of JSON strings, each indicating a reason why a storage backend is unable to transition to "running", why it has transitioned to "failed" or "unknown", and/or why it is at risk of transitioning to "failed".
Defined values are:

* Minimum length: 1
* Maximum length: 127


|managedState
|string
|False
a|JSON string containing a value indicating the management state of the storage backend.
Defined values are:

* "pending" - The storage backend is scheduled to be discovered or added
* "unmanaged" - The storage backend is in a "discovered" state, is not under management, and is eligible for management
* "managed" - The storage backend is in a "running" or "unknown" state and is under management


|managedStateUnready
|array[string]
|False
a|JSON array of JSON strings, each indicating a reason why the storage backend is ineligible to be managed.
Defined values are:

* Minimum length: 1
* Maximum length: 127


|healthState
|string
|False
a|JSON string containing a value indicating the health state of the storage backend.
Defined values are:

* "indeterminate" - The health of the resource cannot be determined (for example, due to lack of connectivity)
* "normal" - The resource has no known issues and can provide services in accordance with the interface specification
* "warning" - The resource has known issues that do not prevent it providing services in accordance with the interface specification
* "critical" - The resource has known issues that prevent it from providing services in accordance with the interface specification


|healthStateUnready
|array[string]
|False
a|JSON array of JSON strings, each indicating a reason why a storage backend is not in a normal health state.
Defined values are:

* Minimum length: 1
* Maximum length: 127


|protectionState
|string
|False
a|JSON string containing a value indicating the protection state of the storage backend. "unknown" for ONTAP.
Defined values are:

* "protected" - The storage backend has a protection policy defined and is in conformance with that policy
* "partial" - The storage backend has a protection policy defined but is out of conformance with that policy
* "none" - The storage backend is not protected
* "unknown" - The storage backend protection policy conformance cannot be determined
* enum: ["protected", "partial", "none", "unknown"]
* example: protected


|protectionStateUnready
|array[string]
|False
a|JSON array of JSON strings, each indicating a reason why a protection policy is out of conformance.
Defined values are:

* Minimum length: 1
* Maximum length: 127


|ontap
|link:#ontap[ontap]
|False
a|JSON object containing specific information related to ONTAP clusters.

* additionalProperties: false


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|False
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-storageBackend",
  "version": "1.3",
  "backendName": "st1-46"
}
====

== Response

```
Status: 204, Indicates if the storageBackend resource was updated.
```

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#ontap]
[.api-collapsible-fifth-title]
ontap

JSON object containing specific information related to ONTAP clusters.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|backendManagementIP
|string
|False
a|JSON string containing the IP address used to connect to this ONTAP cluster.


|managementIPs
|array[string]
|False
a|JSON array of JSON strings containing the list of all possible management IPs used to connect to this ONTAP cluster.
This is used to correlate backends detected through Trident and storage backends in Astra.

* uniqueItems: 1


|===


[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


[#invalidFields]
[.api-collapsible-fifth-title]
invalidFields

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid request body field


|reason
|string
|True
a|Reason why the request body field is invalid


|===


//end collapsible .Definitions block
====
