---
sidebar: sidebar
api: true
explorer: true
permalink: 'reference/put-accounts-core-v1-users-groups-.html'
summary: 'Modify a group for a user'
---

= Modify a group for a user

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups/{group_id}`#



Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|user_id
|string
|path
|True
a|ID of the containing user resource


|group_id
|string
|path
|True
a|ID of the group collection to list


|===

== Request Body

Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-group"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"


|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|False
a|The name of the group resource.
If not specified on create, the value will be set to

* first Common Name (CN) Relative Distinguished Names (RDN) if found in the authID,
* authID, otherwise.
If not specified on update, the value will be preserved without modification.
Defined values are:
* Minimum length: 1
* Maximum length: 2048


|authProvider
|string
|False
a|The authentication provider for the group resource.
Defined values are:

* "ldap"


|authID
|string
|False
a|The Distinguished Name (DN) for an LDAP group.
Defined values are:

* Minimum length: 1
* Maximum length: 2048


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|False
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-group",
  "version": "1.1",
  "name": "my-qa-group",
  "authID": "CN=QA,CN=Groups,DC=example,DC=com"
}
====

== Response

```
Status: 204, Indicates if the group resource was updated.
```

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/7",
  "title": "Invalid JSON payload",
  "detail": "The request body is not valid JSON.",
  "status": "400"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Response

```
Status: 500, Internal server error
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


//end collapsible .Definitions block
====
