---
sidebar: sidebar
api: true
explorer: false
permalink: 'reference/put-accounts-k8s-v1-apps-executionhooks-.html'
summary: 'Modify an execution hook for an app'
---

= Modify an execution hook for an app

[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks/{executionHook_id}`#



Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.

*Side Effects*

* Updating an existing execution hook will impact any future actions of applications that use the updated execution hook.


== Parameters

[cols=5*,options=header]
|===
|Name
|Type
|In
|Required
|Description

|account_id
|string
|path
|True
a|ID of the containing account resource

* example: {{.Account}}


|app_id
|string
|path
|True
a|ID of the containing app resource


|executionHook_id
|string
|path
|True
a|ID of the executionHook collection to list


|===

== Request Body

Replaces the entire stored resource with the supplied JSON request body while preserving key values that are not user-modifiable.

*Side Effects*

* Updating an existing execution hook will impact any future actions of applications that use the updated execution hook.
                   

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|Media type of the resource.
Defined values are:

* "application/astra-executionHook"


|version
|string
|True
a|Version of the resource.
Defined values are:

* "1.0"
* "1.1"
* "1.2"
* "1.3"


|id
|string
|False
a|Globally unique identifier of the resource.
Defined values are:

* Conforms to the UUIDv4 Schema


|name
|string
|False
a|JSON string containing a user-specified name for the resource.
Defined values are:

* Minimum length: 1
* Maximum length: 63
Name must be unique across all execution hook resources.


|hookType
|string
|False
a|JSON string defining the hook type.
Defined values are:

* "netapp" - NetApp provided execution hook.
* "custom" - Tied to a specific app ID.
Execution hook resources with hookType "netapp" are read only.


|matchingCriteria
|array[link:#matchingCriteria[matchingCriteria]]
|False
a|JSON array of JSON objects describing the match criteria for the execution hook.  When multiple matchingCriteria are specified a logical AND is applied to criteria.
Defined values are:

* Minimum items: 0
* Maximum items: 10


|action
|string
|False
a|JSON string indicating which action the execution hook will run assuming the match criteria are met.
Defined values are:

* "snapshot"
* "backup"
* "restore"
* "failover"


|stage
|string
|False
a|JSON string indicating the stage during the action that the hook will be executed.
Defined values are:

* "pre" - The execution hook will be run before the specified action.
* "post" - The execution hook will be run after the specified action.
Values for action "snapshot" are "pre" and "post".
Values for action "backup" are "pre" and "post".
Value for action "restore" is "post".
Value for action "failover" is "post".


|hookSourceID
|string
|False
a|JSON string containing the hook source ID that is run through this execution hook.
Defined values are:

* Conforms to the Astra Identifier Schema


|arguments
|array[string]
|False
a|JSON array of JSON strings for the arguments to the source.
Defined values are:

* Minimum items: 0
* Maximum items: 16
* Minimum length: 0
* Maximum length: 127


|appID
|string
|False
a|JSON string containing the associated ID of the application that this hook is linked to. In essence, other matching criteria, if set.
Defined values are:

* Conforms to the Astra Identifier Schema


|enabled
|string
|False
a|JSON string that indicates if the execution hook is enabled.
Defined values are:

* "true" - The execution hook is enabled and will be run as specified.
* "false" - The execution hook is disabled and will never run.
The default value is "true".


|description
|string
|False
a|JSON string containing a user-specified description for the hook source.
Defined values are:

* Minimum length: 0
* Maximum length: 511


|metadata
|link:#type_astra_metadata_update[type_astra_metadata_update]
|False
a|Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "arguments": [
    "freeze",
    "10"
  ]
}
====

== Response

```
Status: 204, Indicates if the executionHook resource was updated.
```

== Response

```
Status: 401, Unauthorized
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
====

== Response

```
Status: 400, Bad request
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|invalidFields
|array[link:#invalidFields[invalidFields]]
|False
a|List of invalid request body fields


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
====

== Response

```
Status: 409, Conflict
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
====

== Response

```
Status: 403, Forbidden
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
====

== Error

```
Status: 404, Not found
```


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|True
a|

|title
|string
|True
a|

|detail
|string
|True
a|

|status
|string
|True
a|

|correlationID
|string
|False
a|

|===


.Example error response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#matchingCriteria]
[.api-collapsible-fifth-title]
matchingCriteria

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|type
|string
|False
a|JSON string identifying the match criteria type.


|value
|string
|False
a|JSON string containing a regex to match for the given match type.
Regex syntax: https://github.com/google/re2/wiki/Syntax


|===


[#type_astra_label]
[.api-collapsible-fifth-title]
type_astra_label

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|

|value
|string
|True
a|

|===


[#type_astra_metadata_update]
[.api-collapsible-fifth-title]
type_astra_metadata_update

Client and service-specified metadata associated with the resource.
Defined values are:

* Conforms to the Astra Metadata Schema
If not specified on create, a metadata object will be created with no labels.
If not specified on update, the metadata object's labels, creationTimestamp and createdBy, will be preserved without modification.


[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|labels
|array[link:#type_astra_label[type_astra_label]]
|False
a|

|creationTimestamp
|string
|False
a|

|modificationTimestamp
|string
|False
a|

|createdBy
|string
|False
a|

|modifiedBy
|string
|False
a|

|===


[#invalidParams]
[.api-collapsible-fifth-title]
invalidParams

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid query parameter


|reason
|string
|True
a|Reason why the query parameter is invalid


|===


[#invalidFields]
[.api-collapsible-fifth-title]
invalidFields

[cols=4*,options=header]
|===
|Name
|Type
|Required
|Description

|name
|string
|True
a|Name of the invalid request body field


|reason
|string
|True
a|Reason why the request body field is invalid


|===


//end collapsible .Definitions block
====
