---
sidebar: sidebar
permalink: workflows/wf_create_backup.html
keywords:
summary: You can create a backup for a specific application and then use the backup to restore or clone the app.
---

= Create a backup for an app
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a backup for a specific application and then use the backup to restore or clone the app.

== Before you begin

You must have the ID of the app you want to back up. If needed you can use the workflow link:wf_list_man_apps.html[List the apps] to locate the application.

== Create a backup

Perform the following REST API call.

.HTTP method and endpoint

This REST API call uses the following method and endpoint.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups
|===

.Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl examples for this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|app id
|Path
|Yes
|Identifies the application where the backup will be created.
|JSON
|Body
|Yes
|Provides the parameters for the backup. See the example below.
|===

.Curl example: Create a backup for the app
[source,curl]
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v1/apps/$APP_ID/appBackups" \
--include \
--header "Content-Type: application/astra-appBackup+json" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \ 
--data  @JSONinput

.JSON input example
[source,json]
{
  "type": "application/astra-appBackup",
  "version": "1.1",
  "name": "backup-david-1"
}

