---
sidebar: sidebar
permalink: workflows/wf_list_snapshots.html
keywords:
summary: You can list the snapshots that have been taken for a specific application.
---

= List the snapshots
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can list the snapshots that have been taken for a specific application.

=== Before you begin

You must have the ID of the app you want to list the snapshots for. If needed you can use the workflow link:wf_list_man_apps.html[List the apps] to locate the application.

=== 1. List the snapshots

Perform the following REST API call.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/accounts/{account_id}/k8s/v1/apps/{app_id}/appSnaps
|===

===== Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl examples for this step.

[cols="15,10,10,65"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|app id
|Path
|Yes
|Identifies the application owning the listed snapshots.
|count
|Query
|No
|If `count=true` the number of snapshots is included in the metadata section of the response.
|===

===== Curl example: Return all snapshots for the app
[source,curl]
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'

===== Curl example: Return all snapshots for the app and the count
[source,curl]
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps?count=true' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'

===== JSON output example
[source,json]
{
    "items": [
        {
            "type": "application/astra-appSnap",
            "version": "1.1",
            "id": "b8b88603-1026-4031-a705-ce357e62e72c",
            "hookState": "success",
            "metadata": {
                "createdBy": "240cda43-2679-4c2c-9bc7-364383ce463d",
                "creationTimestamp": "2022-10-25T11:44:10Z",
                "modificationTimestamp": "2022-10-25T11:44:10Z",
                "labels": []
            },
            "snapshotCreationTimestamp": "2022-10-25T11:44:10Z",
            "name": "snapshot-david-1",
            "state": "failed",
            "stateUnready": [
                "Converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion."
            ]
        }
    ],
    "metadata": {
        "count": 1
    }
}
