---
sidebar: sidebar
permalink: python/astra_toolkits.html
keywords:
summary:
---

= NetApp Astra Toolkits
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Astra Toolkits is an open source package you can use to automate an Astra Control deployment. The package is also a valuable resource for learning about the Astra Control REST API perhaps as part of creating your own automation platform.

== Two related software tools

The package includes two different though related tools which operate at different levels of abstraction to access the Astra Control REST API.

==== Astra Python SDK

The Astra Control Python SDK provides the core platform functionality. It includes a set of classes which abstract the underlying REST API calls. The classes support administrative actions on various Astra Control resources, including apps, backups, snapshots, and clusters.

The SDK is provided in the single `astraSDK.py` file. You can import the code into your environment and use it directly.

==== Toolkit script

In addition to the Astra Python SDK, the `toolkit.py` script is also available. This script operates at a higher level abstraction by providing specific administrative actions defined internally as Python functions. The script imports the Astra Python SDK and makes calls to the underlying SDK classes as needed.

== How to access

You can access the NetApp Astra Control Python SDK in one of two ways.

==== Python package

The NetApp Astra Control Python SDK is available at https://pypi.org/[Python Package Index^] under the name *netapp-astra-toolkits*. The package is assigned a version number and will continue to be updated as needed. You must use the *PiP* package management tool to install the package at this site into your environment.

==== GitHub source code

The source code for the Astra Control Python SDK is also available at GitHub. Some of the content includes:

* `astraSDK.py` (Python classes)
* `toolkit.py` (function-based script)
* Detailed requirements and installation instructions

You can clone the https://github.com/NetApp/netapp-astra-toolkits[GitHub: Netapp/netapp-astra-toolkits^] repository to your local environment.

==== Installation and basic requirements

There are several options when installing the package and preparing to use it.

==== Summary of the installation options

* Use Pip to install the package into your Python environment
* Clone the Git Hub repository and either:
** Copy the code files so that they are accessible to your client code
** Deploy the package as a Docker container which includes everything you need

Refer to the PyPI and GitHub pages for more information.

==== Basic requirements

You must prepare to be able to install and use the SDK and related toolkit script. The requirements fall into two main categories.

==== Astra Control environment

Whether directly using the Python classes in `astraSDK.py` or the functions in the higher level `toolkit.py` script, ultimately you will be accessing the REST API at an Astra Control deployment. Because of this you'll need an Astra account along with an API token. See link:../get-started/before_get_started.html[Before you begin] in the *Get started* section of the documentation for more information.

==== NetApp Astra Control Python SDK

There are several prerequisites related to the Python environment. You must use Python 3.5 or later. In addition, there are several Python packages that are also required. See the GitHub repository page or PyPI package page for more information.

== Summary of helpful resources

A summary of the resources you'll need to get started is presented below.

* https://pypi.org/project/netapp-astra-toolkits/[PyPI: NetApp Astra Toolkits^]
* https://github.com/NetApp/netapp-astra-toolkits[GitHub: Netapp/netapp-astra-toolkits^]
