---
sidebar: sidebar
permalink: get-started/get_api_token.html
keywords:
summary:
---

= Get an API token
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You need an Astra API token to use the Astra Control REST API.

== Introduction

The API token identifies a caller to Astra and must be included with every REST API call. Note the following:

* You can generate an API token at the Astra web user interface.
* The token must be carried in the `Authorization` HTTP request header.
* A token never expires after it is created.
* You can revoke a token at the Astra web user interface.

.Related information

* link:../additional/revoke_token.html[Revoke an API token]

== Create an Astra API token

The following steps describe how to create an Astra API token.

.Before you begin

You need credentials for an Astra account.

.About this task

This task generates an API token at the Astra web interface. You should also retrieve the account ID which is also needed when making an API calls.

.Steps

. Sign in to Astra using your account credentials.
+
Access the following site for Astra Control Service: https://astra.netapp.io/[https://astra.netapp.io^]

. Click the figure icon at the top right of the page and select *API access*.

. Click *Generate API token* on the page and in the popup window click *Generate API token*.

. Click the icon to copy the token string to the clipboard and save it in your editor.

. Copy and save the account id which is available on the same page.

.After you finish

When you access the Astra Control REST API through Curl or a programming language, you must include the API bearer token in the HTTP `Authorization` request header.
