---
sidebar: sidebar
permalink: get-started/online_api_ref.html
keywords: reference, api reference
summary: You can access the details of the Astra Control REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API.
---

= Online API reference
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can access the details of the Astra Control REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API.

.Before you begin

You need an account for Astra Control Center or Astra Control Service. The procedure for generating a token is the same for both Astra deployment models, only the URL used to access Astra is different. Also see link:../reference/overview.html[API reference].

.Steps

. Sign in to Astra using your account credentials.
+
Access the following site for Astra Control Service: link:https://astra.netapp.io[https://astra.netapp.io^].
+
For Astra Control Center, use the URL for your local environment as established during installation.

. Click the figure icon at the top right of the page and select *API access*.

. At the top of the page click the URL displayed under *API Documentation*.

. Provide your account credentials again if prompted.
